name: Release

on:
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get the repository name
        id: get_repo_name
        run: echo ::set-output name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Create Zip File
        uses: thedoctor0/zip-release@master
        if: startsWith(github.ref, 'refs/tags/')
        with:
          filename: '${{ steps.get_repo_name.outputs.REPOSITORY_NAME }}.zip'
          exclusions: '.babelrc
            .circleci/config.yml
            .deployignore
            .distignore
            .DS_Store
            .editorconfig
            .eslint*
            .idea
            .phpcs.xml
            .phpcs.xml.dist
            .travis.yml
            .vscode
            *.git*
            *.lock
            *.log
            *.sql
            *.tar.gz
            *.zip
            behat.yml
            bin
            bitbucket-pipelines.yml
            circle.yml
            composer*
            dependencies.yml
            Gruntfile.js
            gulp*
            multisite.*
            node_modules
            package*
            phpcs*
            phpunit*
            README.md
            src
            stylelint*
            tests
            Thumbs.db
            tsconfig.json
            vendor
            webpack.config.js
            wp-cli.local.yml'
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
            files: ${{ steps.get_repo_name.outputs.REPOSITORY_NAME }}.zip
            name: Version ${{ steps.get_version.outputs.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
